### ISSUE TITLE
findavgvalues

### ISSUE THREAD

**Issue by dmd** [dmd/stabilitycalc#13]
What is the file `findavgvalues`?

(a) It seems to duplicate some functionality found elsewhere; specifically, it looks almost like it's an older, less functional version of stabilitysummary.

(b) It does not currently work; it refers to the variable `whichscan`, which is not defined.

Can this file be removed?

**Comment by bbfrederick** [comment]
It’s a utility for generating the sensitivity maps for the phased array coils, for selecting the placement of test voxels for coil uniformity and inter-coil correlation.  I used it when I first set up the stability scanning.  Something like it should probably be included with stabiltycalc for generating profiles for new/different coils, but for now it can be hidden in a subdirectory, I think.

Blaise
