### ISSUE TITLE
stabilitysummary: NONBIRN works, BIRN fails

### ISSUE THREAD

**Issue by dmd** [dmd/stabilitycalc#23]
The NONBIRN report works. All BIRN images come out empty, and the report claims no scans have run since the unix epoch.

**Comment by bbfrederick** [comment]
That’s peculiar, as all of the runs I gave you to test were BIRN runs.  IIRC if the phantom is round and of the right size, and is scanned with the right protocol, it assumes it is a BIRN phantom, so one of those tests seems to be failing…

**Comment by dmd** [comment]
This is something I'm confused about. 

Two issues:
1) singleslice, multiflip10, and multiflip77 get `objectname="BIRN Phantom"`, but `is_birn_protocol = False` and `protocolname = "Unknown"`

Therefore, one of these tests is false: `(xsize != 64) or (ysize != 64) or (numslices != 28) or (tr != 2.0)`

See: https://github.com/dmd/stabilitycalc/blob/4d8e287ab4a9c9b23326ba4ce85970973cb86f51/stabilitycalc.py#L174-185

2) In your original code, which I'm still mimicking,  processstability seems to run stabilitysummary on the same files for birn and nonbirn. I'm unclear on how this doesn't end up duplicating the same files in both places: https://github.com/dmd/stabilitycalc/blob/0a3b4da56d1d3ba7dafa5204fe4119b91bf2f1ec/processstability#L40-41

Can you @bbfrederick take a look at https://github.com/dmd/stabilitycalc/blob/master/processstability.py and tell me if you see something obvious?

**Comment by dmd** [comment]
So like - I'm confused as to what there should even BE in the `stability/3T/birn` vs `stability/3T/nonbirn` folders if there is only birn data.

**Comment by bbfrederick** [comment]
There is occasionally, but rarely nonbirn data.  We have some water phantoms that we scan from time to time, and they get filed away in nonbirn.  But it’s less than 5% of the data, I’d say.  Maybe much less.

**Comment by dmd** [comment]
Ok, yeah, so my questions stand -- I don't see where in your original code there is any provision for not duplicating everything in both places. Maybe I'm missing something obvious.

**Comment by bbfrederick** [comment]
Stabilitycalc checks for a BIRN phantom:

BIRNphantom_radiuscheck=sf.limitcheck(object_radius_mm,thelimitdict['BIRNphantom_rad'])
BIRNphantom_shapecheck=sf.limitcheck(object_shape,thelimitdict['BIRNphantom_shape'])
BIRNphantom_snrcheck=sf.limitcheck(object_snr,thelimitdict['BIRNphantom_snr'])
if((BIRNphantom_radiuscheck < 2) and (BIRNphantom_shapecheck < 2)):
    objecttype=BIRNphantom
    objectname="BIRN_phantom"
    print "setting objecttype to BIRNphantom"


Then when you run stabilitysummary and stabilitysummary_nonbirn they check each file and see if it is a BIRN phantom or not (this is stabilitysummary:
doBIRN=True

if doBIRN:
    print 'called as stabilitysummary (BIRN)'
    TargetisBIRNphantom=True
else:
    print 'called as stabilitysummary_nonbirn (NONBIRN)'
    TargetisBIRNphantom=False

and files are only used if they match the criterion for that run:

            if ObjectisBIRNphantom==TargetisBIRNphantom:
                if datadict[filenumber_TARGET]['Coil']=='TxRx_Head':
                    num_cp_TARGET=num_cp_TARGET+1
                if datadict[filenumber_TARGET]['Coil']=='32Ch_Head':
                    num_32_TARGET=num_32_TARGET+1
                if datadict[filenumber_TARGET]['Coil']=='HeadMatrix':
                    num_12_TARGET=num_12_TARGET+1
                filenumber_TARGET=filenumber_TARGET+1


So the first thing I’d check is in the procresults/analysissummary.txt files for each of the runs and make sure the “Object” is BIRN_phantom

**Comment by dmd** [comment]
Also 9ab9deb9001f0941815aa704f47f4a8029d320cb -- "BIRN phantom" without underscore now.
